[package]
name = "full_page_text_history_search"
version = "0.1.0"
authors = ["Jeffrey Brusseau <bobajeff82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
